### PR TITLE
273 claim 00 message queue

### LINKED ISSUE #273: CLAIM-00: Message queue
# Initial Issue
When claiming NFTs for the orders, the current design create errors and congestion by trying to only use one wallet at a time. This create errors because of the design of the blockchain, with nonce issues and transactions per block.

# Solutions
## Message queue - QStash

1. Use Multiple Wallets
Purpose: Overcome nonce and block space limitations by distributing transactions across several wallets.
Implementation: Securely generate and manage multiple wallets. Ensure each wallet has sufficient funds for transaction fees.

2. Implement a Message Queue
Choice of Technology: Use QStash or a similar message queue service for its simplicity and reliability.
Benefits: Decouples the transaction initiation process from the execution, allowing for efficient management of transaction requests and retries in case of failures.

3. Design System Architecture
Claim HTTP API Route: Receives external requests to claim NFTs and enqueues them into the message queue with all necessary details (contract address, token ID, etc.).
Worker Service: Listens to the message queue. When a message is received, it selects an available wallet and initiates the NFT claim transaction.
Wallet Management: Use Redis or a similar fast-access data store to keep track of wallet statuses (free or busy). Before a wallet initiates a transaction, mark it as busy, and once the transaction is complete or fails, mark it as free.

4. Concurrency and Rate Limiting
Implementation: Ensure the worker service respects the rate limits of the blockchain network and efficiently manages wallet usage without causing nonce conflicts.
Strategy: Implement logic to select a free wallet from Redis, ensuring atomic operations to avoid race conditions.

5. Error Handling and Retries
Mechanism: Implement robust error handling within the worker service to manage transaction failures, including retries (limited to three with QStash) with exponential backoff.
Wallet Status Reset: In case of a transaction failure, ensure the wallet status is correctly reset to allow for future transactions.

## Own claim queue - KV
 - [x] minterTemporaryWallet : 
 -> address
 -> privateKey
-> eventPassId opt
-> packId opt
-> createdAt

- [x] packNftSupply/eventPassNft : 
-> isDelivered

image

### PR DESCRIPTION
**Pull request by AlexandreG-tech**
## **Type**
enhancement, bug_fix

___

## **Description**
- Introduced `isDelivered` field to track delivery status of NFTs.
- Added `MinterTemporaryWallet` type for managing temporary wallets for minters.
- Implemented minter temporary wallet creation in NFT collection deployment.
- New API endpoint and cron job for processing orders using Redis.
- Enhanced order processing in Payment Admin to use Redis.
- Added integration and unit tests for new features and modifications.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>6 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Add Delivery Status and Minter Temporary Wallet Types</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/gql/shared/types/src/generated/index.ts
<li>Added <code>isDelivered</code> field to <code>EventPassNft</code> and <code>PackNftSupply</code> types.<br> <li> Introduced <code>MinterTemporaryWallet</code> type with fields for managing <br>temporary wallets for minters.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-45f88726b08ae3e5de33349ab408a92d15c771f0df9d1f4027ff1ce2644c99cf">+360/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Implement Minter Temporary Wallet Creation in NFT Collection</code></dd></summary>
<hr>

libs/nft/thirdweb-organizer/src/index.ts
<li>Added wallet creation logic in <code>getContractWithClaimConditions</code>.<br> <li> Included <code>minterTemporaryWallet</code> in the return object of contract <br>deployment functions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-80b26817489489d8498897af632d05d0f4662c8d8ebdcb70de6613f0297b72d6">+35/-8</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>payment-admin.ts</strong><dd><code>Update Payment Admin to Use Redis for Order Processing</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/payment/admin/src/lib/payment-admin.ts
<li>Removed <code>refundPartialPayment</code> method.<br> <li> Modified <code>confirmedStripeCheckoutSession</code> to use Redis for order <br>processing.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-d5b42e9028bd5be069e6e012324c6ac4abb3b9b72a12b32902df391daf9f45bd">+15/-33</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Implement API Endpoint for Order Claim Processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/pages/api/orders/claim/index.ts
<li>New API endpoint for processing claimed orders.<br> <li> Utilizes <code>multicallClaim</code> for efficient order processing.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-434b178851cd510d14486d3c7a66f95230121fb680f09069f7a0917dcbbb4388">+48/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nft-thirdweb-api.ts</strong><dd><code>Add Multicall Claim Method for Batch NFT Processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/nft/thirdweb-admin/src/lib/nft-thirdweb-api.ts
<li>Added <code>multicallClaim</code> method for batch processing of NFT claims.<br> <li> Utilizes temporary wallets for signing transactions.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-150c80ec08729dcba4ddde00c6d25b1897f7c9852ffc033e3407d5f122b493e7">+93/-4</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>processRedisOrders.ts</strong><dd><code>New Cron Job for Processing Redis Orders</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

apps/web/app/crons/processRedisOrders.ts
<li>New cron job for processing Redis orders.<br> <li> Invokes the orders-cron handler for order processing.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-4fba72fa233373d7c0dc6fde34192f861d3c22ba1d14a1480577a83e70403853">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Tests
</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.integration.test.ts</strong><dd><code>Integration Tests for Orders Cron Functions and Handler</code>&nbsp; &nbsp; </dd></summary>
<hr>

libs/features/orders-cron/src/index.integration.test.ts
<li>Integration tests for minor functions and handler in the orders-cron <br>feature.<br> <li> Tests for <code>setOrdersToBusy</code>, <code>deleteOrders</code>, and the main handler <br>function.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-a32ec4d9ba3df15f8969bf94e7124b6d96d4275676752bdfdc4c49fdc81213b1">+219/-0</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nft-thirdweb-api.spec.ts</strong><dd><code>Add Tests for Multicall Claim in NFT Claimable</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/nft/thirdweb-admin/src/lib/nft-thirdweb-api.spec.ts
<li>Mocked <code>@thirdweb-dev/sdk</code> for NFT claim tests.<br> <li> Added tests for <code>multicallClaim</code> method to ensure it updates order <br>statuses correctly.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-3ccc4a1d46881a7ab0a2f65bb2398ef21b47c99c144f0eb6214ba97825b11b03">+40/-63</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nftCollection.integration.test.ts</strong><dd><code>Integration Tests for NFT Collection with Temporary Wallet Creation</code></dd></summary>
<hr>

libs/nft/thirdweb-organizer/src/nftCollection.integration.test.ts
<li>Mocked <code>ethers</code> to test wallet creation.<br> <li> Integration tests for deploying NFT collections with temporary wallet <br>creation.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/275/files#diff-b3d88963320227a70f06c3fdb4d092a57c26c2d41a4d70bbb9c37b5452bea233">+48/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> ✨ **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

File: apps/web/pages/api/orders/claim/index.ts
Comment (sebpalluel) [inline apps/web/pages/api/orders/claim/index.ts:1]: Add test because this route is now far more complicated that the former one:

- Unit test for error 405 and 400.
- Integration test for happy path with minter wallet not busy and an other one where minter wallet is busy (not clear in the code here what's happening in that case).

File: libs/nft/thirdweb-organizer/src/index.ts [hunk 1]
```diff
@@ -167,14 +175,20 @@ export class NftCollection {
         maxClaimablePerWallet: 0,
         snapshot: [
           {
-            address: env.NEXT_PUBLIC_THIRDWEB_MASTER_ADDRESS,
+            address: walletAddress,
```
Comment (sebpalluel) [inline libs/nft/thirdweb-organizer/src/index.ts:178]: Delete all occurrences of `NEXT_PUBLIC_THIRDWEB_MASTER_ADDRESS` in project because it's not used anymore

**Review by sebpalluel — CHANGES_REQUESTED** [review]

File: apps/web/pages/api/orders/claim/index.integration.test.ts [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+
+    await kv.set('0xtestwalletaddress11', 'busy');
+
+    await handler(mockReq, mockRes);
+
+    expect(mockRes.status).toHaveBeenCalledWith(500);
+    expect(mockRes.json).toHaveBeenCalledWith(expect.any(Object));
+    await kv.del('0xtestwalletaddress11');
+  });
+});
```
Comment (sebpalluel) [inline apps/web/pages/api/orders/claim/index.integration.test.ts]: Well it shouldn't handle a busy wallet with an error 500 because it's an expected behaviour that the wallet can be busy sometime. It should be handled gracefully.

**Review by sebpalluel — CHANGES_REQUESTED** [review]

**Review by sebpalluel — APPROVED** [review]
