### PR TITLE
267 26012024 bug report

### LINKED ISSUE #267: 26/01/2024 Bug Report
old ticket can be found [here](https://github.com/Offline-Project/marketplace/issues/234)

- [x] Stripe Webhook 500 Internal Server Error ?
- [x] Back-office EventPassDelayedReveal white screen
- [x] _ilike or another method in queries involving alchemy to be case insensitive
- [x] Bytescale file downloading and path/permission after a transfer

### PR DESCRIPTION
**Pull request by AlexandreG-tech**
## **Type**
Bug fix, Enhancement

___

## **Description**
- The PR primarily focuses on the refactoring of the `revealDelayedContract` function. The function was previously defined in `revealDelayedContract.ts` and `nft-thirdweb-api.ts`, but it has been removed from these files.
- The `revealDelayedContract` function has been added to the `NftCollection` class in `thirdweb-organizer/src/index.ts`.
- The `EventPassContractRevealButtonClient` component has been updated to use the `ThirdwebSDK` for revealing contracts.
- The GraphQL queries in `index.tsx` and `eventParameters.query.gql` have been updated to use `_ilike` instead of `_eq` for case insensitive match.
- A new translation for `success-description` has been added to `fr.json`.

___

## **Changes walkthrough**
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>deployCollectionWrapper.ts</strong><dd><code>Added import for NftCollection in deployCollectionWrapper.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/features/back-office/events/src/lib/actions/deployCollectionWrapper.ts
- Added an import statement for `NftCollection` from <br>  `@nft/thirdweb-organizer`.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-f14ec5080841102c088015af4bb9d3aef3a9ecc768c644b7cd66f7ad51d6efe8">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Miscellaneous</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>revealDelayedContract.ts</strong><dd><code>Removed revealDelayedContract.ts file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/features/back-office/events/src/lib/actions/revealDelayedContract.ts
- The entire file was removed, which previously contained the <br>  `revealDelayedContract` function.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-f369fc6b24a4a8cd124cb9564e6e5f0d024fb7afe359d8a13cdbb82cb582c5fd">+0/-10</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>nft-thirdweb-api.ts</strong><dd><code>Removed revealDelayedContract function in nft-thirdweb-api.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/nft/thirdweb-admin/src/lib/nft-thirdweb-api.ts
- Removed the `revealDelayedContract` function.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-150c80ec08729dcba4ddde00c6d25b1897f7c9852ffc033e3407d5f122b493e7">+0/-49</a>&nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Enhancement</strong></td><td><details><summary>3 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>EventPassContractRevealButtonClient.tsx</strong><dd><code>Updated EventPassContractRevealButtonClient to use ThirdwebSDK</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/features/back-office/events/src/lib/molecules/EventPassCardFooter/EventPassContractRevealButtonClient.tsx
- Added import statements for `useAuthContext`, `NftCollection`, `<br>  ``ThirdwebSDK`, `<br>  `and `<br>  ``env`.
- Removed the import statement for `revealDelayedContract`.
- Updated the `revealContract` function to use the `ThirdwebSDK` for <br>  revealing contracts.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-5f9fe9fcb67d7bddb75b6fd39c1ad103485b6023b71122858df8be4ffd1b4788">+17/-3</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>action.ts</strong><dd><code>Added new functions in thirdweb-organizer action.ts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/nft/thirdweb-organizer/src/action.ts
- Added `getEventPassDelayedRevealPassword` and `saveRevealIntoDb` <br>  functions.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-979b6ef9b050567219e1a772e5d6449136db534623283c47496e746df4235a35">+19/-0</a>&nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.ts</strong><dd><code>Added revealDelayedContract function in NftCollection class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/nft/thirdweb-organizer/src/index.ts
- Added `revealDelayedContract` function in `NftCollection` class.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-80b26817489489d8498897af632d05d0f4662c8d8ebdcb70de6613f0297b72d6">+44/-0</a>&nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Tests</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>examples.tsx</strong><dd><code>Removed revealDelayedContract mock in EventPassNftFilesTable examples</code></dd></summary>
<hr>

libs/features/back-office/events/src/lib/molecules/EventPassNftFilesTable/examples.tsx
- Removed import and mock for `revealDelayedContract`.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-26ad6e13d3af1b3c7b35faf7a74ed82693a7997fde833329b6f77180c554cf38">+0/-4</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>EventSheet.stories.tsx</strong><dd><code>Removed revealDelayedContract usage in EventSheet stories</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/features/back-office/events/src/lib/organisms/EventSheet/EventSheet.stories.tsx
- Removed import and usage of `revealDelayedContract`.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-036a083ca21ce3857d60c16e612304ca55f6ae9ab4803d33e771d8db9fb61434">+0/-15</a>&nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Bug fix</strong></td><td><details><summary>2 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>index.tsx</strong><dd><code>Updated GraphQL queries to use case insensitive match</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/gql/user/react-query/src/generated/index.tsx
- Replaced `_eq` with `_ilike` in GraphQL queries to perform case <br>  insensitive match.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-3ada331694fbeca247f1358954f576fb18952a2f776256a8a7f605285c65fd64">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>eventParameters.query.gql</strong><dd><code>Updated GraphQL queries to use case insensitive match</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/gql/user/api/src/queries/pass/eventParameters.query.gql
- Replaced `_eq` with `_ilike` in GraphQL queries to perform case <br>  insensitive match.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-383801d2f4084a8713229a33f92df69cf0628a397950c4079376ed269811f212">+6/-6</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr><tr><td><strong>Documentation</strong></td><td><details><summary>1 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>fr.json</strong><dd><code>Added new translation in fr.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

libs/next/i18n/src/messages/fr.json
- Added a new translation for `success-description` under <br>  `EventPassContractRevealButtonClient`.
    </details>
  </td>
  <td><a href="https://github.com/Offline-Project/marketplace/pull/268/files#diff-c887ffa33c39eae1df0b881ea9910d1ce6bfed6e5f715e170f70be64f5ef929d">+2/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></details></td></tr></tr></tbody></table><hr>

<details> <summary><strong>✨ Usage guide:</strong></summary><hr> 

**Overview:**
The `describe` tool scans the PR code changes, and generates a description for the PR - title, type, summary, walkthrough and labels. The tool can be triggered [automatically](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) every time a new PR is opened, or can be invoked manually by commenting on a PR.

When commenting, to edit [configurations](https://github.com/Codium-ai/pr-agent/blob/main/pr_agent/settings/configuration.toml#L46) related to the describe tool (`pr_description` section), use the following template:
```
/describe --pr_description.some_config1=... --pr_description.some_config2=...
```
With a [configuration file](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#working-with-github-app), use the following template:
```
[pr_description]
some_config1=...
some_config2=...
```

<table><tr><td><details> <summary><strong> Enabling\disabling automation </strong></summary><hr>

- When you first install the app, the [default mode](https://github.com/Codium-ai/pr-agent/blob/main/Usage.md#github-app-automatic-tools) for the describe tool is:
```
pr_commands = ["/describe --pr_description.add_original_user_description=true" 
                         "--pr_description.keep_original_user_title=true", ...]
```
meaning the `describe` tool will run automatically on every PR, will keep the original title, and will add the original user description above the generated description. 

- Markers are an alternative way to control the generated description, to give maximal control to the user. If you set:
```
pr_commands = ["/describe --pr_description.use_description_markers=true", ...]
```
the tool will replace every marker of the form `pr_agent:marker_name` in the PR description with the relevant content, where `marker_name` is one of the following:
  - `type`: the PR type.
  - `summary`: the PR summary.
  - `walkthrough`: the PR walkthrough.

Note that when markers are enabled, if the original PR description does not contain any markers, the tool will not alter the description at all.
        

</details></td></tr>

<tr><td><details> <summary><strong> Custom labels </strong></summary><hr>

The default labels of the `describe` tool are quite generic: [`Bug fix`, `Tests`, `Enhancement`, `Documentation`, `Other`].

If you specify [custom labels](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md#handle-custom-labels-from-the-repos-labels-page-gem) in the repo's labels page or via configuration file, you can get tailored labels for your use cases.
Examples for custom labels:
- `Main topic:performance` - pr_agent:The main topic of this PR is performance
- `New endpoint` - pr_agent:A new endpoint was added in this PR
- `SQL query` - pr_agent:A new SQL query was added in this PR
- `Dockerfile changes` - pr_agent:The PR contains changes in the Dockerfile
- ...

The list above is eclectic, and aims to give an idea of different possibilities. Define custom labels that are relevant for your repo and use cases.
Note that Labels are not mutually exclusive, so you can add multiple label categories.
Make sure to provide proper title, and a detailed and well-phrased description for each label, so the tool will know when to suggest it.        

</details></td></tr>

<tr><td><details> <summary><strong> Inline File Walkthrough 💎</strong></summary><hr>

For enhanced user experience, the `describe` tool can add file summaries directly to the "Files changed" tab in the PR page.
This will enable you to quickly understand the changes in each file, while reviewing the code changes (diffs).

To enable inline file summary, set `pr_description.inline_file_summary` in the configuration file, possible values are:
- `'table'`: File changes walkthrough table will be displayed on the top of the "Files changed" tab, in addition to the "Conversation" tab.
- `true`: A collapsable file comment with changes title and a changes summary for each file in the PR.
- `false` (default): File changes walkthrough will be added only to the "Conversation" tab.
<tr><td><details> <summary><strong> Utilizing extra instructions</strong></summary><hr>

The `describe` tool can be configured with extra instructions, to guide the model to a feedback tailored to the needs of your project.

Be specific, clear, and concise in the instructions. With extra instructions, you are the prompter. Notice that the general structure of the description is fixed, and cannot be changed. Extra instructions can change the content or style of each sub-section of the PR description.

Examples for extra instructions:
```
[pr_description] 
extra_instructions="""
- The PR title should be in the format: '<PR type>: <title>'
- The title should be short and concise (up to 10 words)
- ...
"""
```
Use triple quotes to write multi-line instructions. Use bullet points to make the instructions more readable.

</details></td></tr>

<tr><td><details> <summary><strong> More PR-Agent commands</strong></summary><hr> 

> To invoke the PR-Agent, add a comment using one of the following commands:  
> - **/review**: Request a review of your Pull Request.   
> - **/describe**: Update the PR title and description based on the contents of the PR.   
> - **/improve [--extended]**: Suggest code improvements. Extended mode provides a higher quality feedback.   
> - **/ask \<QUESTION\>**: Ask a question about the PR.   
> - **/update_changelog**: Update the changelog based on the PR's contents.   
> - **/add_docs** 💎: Generate docstring for new components introduced in the PR.   
> - **/generate_labels** 💎: Generate labels for the PR based on the PR's contents.   
> - **/analyze** 💎: Automatically analyzes the PR, and presents changes walkthrough for each component.   

>See the [tools guide](https://github.com/Codium-ai/pr-agent/blob/main/docs/TOOLS_GUIDE.md) for more details.
>To list the possible configuration parameters, add a **/config** comment.   
 

</details></td></tr>

</table>

See the [describe usage](https://github.com/Codium-ai/pr-agent/blob/main/docs/DESCRIBE.md) page for a comprehensive guide on using this tool.

</details>

### CODE REVIEW

File: libs/features/back-office/events/src/lib/actions/revealDelayedContract.ts
Comment (sebpalluel) [inline libs/features/back-office/events/src/lib/actions/revealDelayedContract.ts:1]: Why not just remove the 'use server' to make it work client side ?

File: libs/features/back-office/events/src/lib/organisms/EventSheet/EventSheet.stories.tsx [hunk 1]
```diff
@@ -226,20 +225,7 @@ export const WithEventPassDelayedRevealToReveal: Story = {
     expect(textElement).toBeInTheDocument();
     const buttonElement = await screen.findByText(/reveal your event pass/i);
     await expect(buttonElement).toBeEnabled();
```
Comment (sebpalluel) [inline libs/features/back-office/events/src/lib/organisms/EventSheet/EventSheet.stories.tsx:228]: Commenting the test is a very bad practice and should be avoided, to delete it make it even worse...

**Review by sebpalluel — DISMISSED** [review]

File: libs/features/organizer/event-actions/src/lib/updateEventPassCart.ts [hunk 2]
```diff
@@ -46,8 +48,9 @@ export async function updateEventPassCart({
         },
       });
   }
-  // give a 404 error, server action bug ?
-  // revalidateTag(`getOrderSum-${eventPassId}`);
-  // revalidateTag(`getEventPassCart-${eventPassId}`);
-  // revalidateTag('getEventPassesCart');
+  if (!isJestRunning()) {
```
Comment (sebpalluel) [inline libs/features/organizer/event-actions/src/lib/updateEventPassCart.ts:51]: Non pq ?
peux mock revalidateTag si besoin

File: libs/features/organizer/event/src/lib/molecules/PassCard/PassCardSelectClient.tsx [hunk 3]
```diff
@@ -24,7 +25,9 @@ export const PassCardSelectClient: React.FC<PassCardSelectClientProps> = ({
   ...boundedNumericStepperProps
 }) => {
   const [isPending, startTransition] = useTransition();
-  const router = useRouter();
+  const { toast } = useToast();
+  const t = useTranslations('Organizer.Event.PassPurchase');
```
Comment (sebpalluel) [inline libs/features/organizer/event/src/lib/molecules/PassCard/PassCardSelectClient.tsx:29]: Ok mais en l'absence du provider sur le server component ça va casser

**Review by sebpalluel — CHANGES_REQUESTED** [review]
